spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: Admin
    password: admin
    virtual-host: rabbit-advanced
springdoc:
  swagger-ui:
    path: /
server:
  port: 8080