spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supermercado
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: Admin
    password: admin
    virtual-host: rabbit-advanced
springdoc:
  swagger-ui:
    path: /
server:
  port: 8081